victorfrye/microsoftgraveyard

- src/Client/wwwroot/data/corpses.json
Will close #29 #30 #31 #32 #33 #34 and #35 plus add Visual SourceSafe, a source control that lived longer than you would imagine.
> feat(corpses): add nine additional dead products from ms history

- .github/workflows/azure-swa.yml
> fix: fail softly on forks when secret is missing

- src/Client/wwwroot/data/corpses.json
> feat(corpses): add sunrise and foxpro

- .devcontainer/devcontainer.json
Add a dev container definition
- Closes #56 
> chore: add devcontainer for gh codespaces support

- src/Client/wwwroot/data/corpses.json
Add headstone for PixelSense
- Closes #57 
- [n/a] Tests added and/or updated
> feat(corpses): add headstone for pixelsense

- src/Client/wwwroot/data/corpses.json
Added a Corpse for Dynamics HR Standalone which died last month
- Closes #61
Tests not needed just data change
> Add Dynamics 365 HR standalone

- src/Client/Client.csproj
- src/Client/Components/Content/Graveyard.razor
- src/Client/Components/Content/SocialButtons.razor
- src/Client/Components/Content/SocialButtons.razor.css
- src/Client/wwwroot/data/corpses.json
Add headstones for Windows Live Essentials products, LightSwitch, Money in Excel, Office Accounting, and Response Point
Remove AOT compilation to reduce download size.
Padding updates to remove horizontal scrolling.
- Closes #67 
- Closes #66 
- Closes #65 
- Closes #63 
- Closes #64 
> feat(corpses): add headstones for live essentials, lightswitch, etc

- src/Client/wwwroot/data/corpses.json
Add the following new corpses:
- XNA
- Midori
- Fahrenheit
- SQL Server Data Mining
- SQL Server English Query
- Closes #70 
- Closes #75 
- Closes #76 
- Closes #78 
- Closes #79 
> feat(corpses): add sql server features, unreleased r+d, and xna

- public/data/corpses.json
> feat(corpses): add publisher

- .github/workflows/azure-swa.yml
> ci(build-deploy): enable concurrency

- public/data/corpses.json
Add two corpses to the graveyard:
- PerformancePoint Server
- ProClarity
- Closes #116 
> feat(corpses): add performancepoint server and proclarity

- public/data/corpses.json
Add [WSA](https://learn.microsoft.com/en-gb/windows/android/wsa/) to the list. RIP.
> Add WSA to corpses.json

- .github/ISSUE_TEMPLATE/1_new_dead_product.md
- .github/ISSUE_TEMPLATE/2_bug_report.md
- .github/ISSUE_TEMPLATE/3_feature_request.md
> chore(issues): update issue template labels

- .github/ISSUE_TEMPLATE/1_new_dead_product.md
- .github/ISSUE_TEMPLATE/2_bug_report.md
- .github/ISSUE_TEMPLATE/3_feature_request.md
- .github/dependabot.yml
- .github/workflows/azure-swa.yml
> docs(issues): update issue templates and labels

- public/images/coffin.svg
- public/images/headstone.svg
- src/components/shared/footer.tsx
Added a floating action button to quickly navigate to about information in footer
- Closes #90 
- [n/a] Tests added and/or updated
> feat(fab): add floating action button for quick nav

- .github/workflows/azure-swa.yml
> fix(perms): allow contributors to gen PR comments

- .eslintrc.json
- .github/CODE_OF_CONDUCT.md
- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/1_new_dead_product.md
- .github/ISSUE_TEMPLATE/2_bug_report.md
- .github/ISSUE_TEMPLATE/3_feature_request.md
- .github/dependabot.yml
- .github/workflows/azure-swa.yml
- .prettierrc.json
- README.md
- next.config.mjs
- package.json
- src/app/layout.tsx
- src/app/page.tsx
- src/components/graveyard/graveyard.tsx
- src/components/providers/darkMode.tsx
- src/components/providers/theme.tsx
- src/components/shared/footer.tsx
- src/components/shared/header.tsx
- src/components/shared/socials.tsx
- src/models/corpse.ts
- src/styles/globals.css
- yarn.lock
> style(prettier): add prettier for opinionated formatting

- public/data/corpses.json
Add Upload Studio to the list of corpses.
- Closes #189 
> feat(corpses): add xbox upload studio to graveyard

- public/data/corpses.json
Add Teams Wiki pages to graveyard
- Closes #192 
> feat(corpses): add ms teams wiki pages

- tests/Core/Tests.csproj
- Duplicates #218 
- Duplicates #219 
- Duplicates #220 
- Duplicates #221 
- Duplicates #222 
> build(deps): bump test proj dependencies

- src/data/corpses.json
> feat(corpses): new headstone for xbox avatars

- LICENSE
- files/corpses.schema.json
- package-lock.json
- package.json
- src/data/corpses.json
> feat(corpses): new headstone for dev home

- src/WebClient/app/components/Graveyard.tsx
- src/WebClient/app/components/Headstone.tsx
- src/WebClient/app/hooks/useCorpse.ts
- src/WebClient/app/types/corpse.ts
> feat: add usecorpse hook and skeleton rendering

- src/WebClient/app/components/Graveyard.tsx
- src/WebClient/app/components/Headstone.tsx
- src/WebClient/eslint.config.js
> fix: remove unused + refactor flat config

- src/WebClient/app/data/corpses.json
https://learn.microsoft.com/en-us/azure-data-studio/whats-happening-azure-data-studio
ADS will be discontinued on February 28, 2026.
> Azure Data Studio

- src/WebClient/app/data/corpses.json
> feat(corpses): add headstone for azure data studio

- src/WebClient/app/components/GraveyardSocials.tsx
> chore: add rel me to socials

- src/WebClient/app/data/corpses.json
Add headstone for Viva Goals
- Closes #301
> feat(corpses): new headstone for viva goals

- .github/workflows/azure-swa.yml
- .github/workflows/bicep.yml
- README.md
- infra/main.bicep
- infra/main.bicepparam
Convert existing infrastructure to code
- n/a
> feat(infra): convert infrastructure to code

- infra/main.bicep
> fix: update default custom domain

- src/WebClient/app/data/corpses.json
> feat(corpses): add headstone for skype

- src/WebClient/app/components/graveyard/corpses.json
Add headstone for Windows Maps
- Closes #338
> feat(corpses): add headstone for windows maps

- .devcontainer/devcontainer.json
- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/1_new_corpse.md
- .github/ISSUE_TEMPLATE/2_bug_report.md
- .github/ISSUE_TEMPLATE/3_feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/dependabot.yml
- README.md
- src/WebClient/prettier.config.js
- Updated issue templates
- Add contributing guide
- Updated PR template
- Cleaned up readme
> docs: update project documentation

- .github/workflows/azure-swa.yml
- Add microsoftgraveyard.com url to prod deployments
> chore: add msg url to prod deploys

- .github/workflows/azure-swa.yml
- .github/workflows/bicep.yml
> chore: lowercase env names

- .github/workflows/codeql.yml
- README.md
> chore: switch to advanced codeql

- src/WebClient/app/corpses.json
Add headstones for all Bing Search APIs, including web, news, custom, and spell check.
- Closes #355
> feat(corpses): add headstones for all bing search apis

- src/WebClient/app/corpses.json
Add headstones for Microsoft Wallet and E-tree.
- Closes #367
> feat(corpses): add headstone for wallet and etree
